title: Texture Theme
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage
<<<<<<< HEAD
baseurl: 
=======
<<<<<<< HEAD
baseurl: 
=======
baseurl: #一般置空就行
>>>>>>> 修改提示
>>>>>>> 修改

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
<<<<<<< HEAD

permalink: /posts/:title/
texture:
  title: Adam Denisov
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: true

  # generate social links in footer
  social_links:
    twitter: thelehhman
    github:  thelehhman
    linkedIn: in/thelehhman
    rss: rss
=======
>>>>>>> 修改
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

<<<<<<< HEAD
=======
permalink: /posts/:title/
>>>>>>> 修改
plugins:
  - jekyll-seo-tag
#  - jekyll-feed

texture:
<<<<<<< HEAD
  title: Adam Denisov
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"
  style: [yellow|red|black|blue|green|purple]
=======
  title: ღinɠڂ sҜჟ
  tagline: ႟༆
  date_format: "%b %-d, %Y"
  style: [qiuri|yuhui|yellow|red|black|blue|green|purple]
>>>>>>> 修改
  showPicker: [false|true] # show the texture selector(development purposes)
  disqus_shortname: games
  analytics_id: '< YOUR ID >'
  show_excerpts: true
  showNav: true

  social_links:
    twitter: thelehhman
    github:  thelehhman
    linkedIn: in/thelehhman # format: locale/username
