title: ღinɠڂ sҜჟ
author: ღinɠڂ sҜჟ
email: 247538236@qq.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage

baseurl: #一般置空就行

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
 
highlighter: rouge

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

permalink: /posts/:year/:month/:day/:title/
plugins:
  - jekyll-seo-tag
#  - jekyll-feed

texture:
  title: ღinɠڂ sҜჟ
  tagline: ႟༆
  date_format: "%b %-d, %Y"
  style: [qiuri|yuhui|yellow|red|black|blue|green|purple]
  showPicker: [false|true] # show the texture selector(development purposes)
  disqus_shortname: games
  analytics_id: '< YOUR ID >'
  show_excerpts: true
  showNav: true

  social_links:
    twitter: mingtsky
    github:  mingtsky
    linkedIn: CHINA/Mingtsky # format: locale/username
